apiVersion: v1
kind: ConfigMap
metadata:
  namespace: '{{ .Values.metadata.namespace }}'
  name: '{{ .Values.metadata.configmap_name }}'
  labels:
    app: '{{ .Values.metadata.app_name }}'
data:
  # -- Directory Params:
  ANYLOG_PATH: '{{ .Values.node_configs.directories.ANYLOG_PATH }}'
  LOCAL_SCRIPTS: '{{ .Values.node_configs.directories.LOCAL_SCRIPTS }}'
  TEST_DIR: '{{ .Values.node_configs.directories.TEST_DIR }}'

  # -- INIT Type --
  INIT_TYPE: '{{ .Values.image.init_type | default "prod" }}'
  DISABLE_CLI: '{{ .Values.image.disable_cli | default "false" }}'
  # Inform system deployment is in Kubernetes format - this set the PROXY_IP value as a valid host
  IS_KUBERNETES: 'true'

  # -- General --
  LICENSE_KEY: {{ .Values.node_configs.general.LICENSE_KEY }}
  NODE_TYPE: '{{ .Values.node_configs.general.NODE_TYPE }}'
  NODE_NAME: '{{ .Values.metadata.app_name }}'
  COMPANY_NAME: '{{ .Values.node_configs.general.COMPANY_NAME }}'

  # -- Networking --
  {{- if ne  .Values.node_configs.networking.OVERLAY_IP "" }}
  OVERLAY_IP: '{{ .Values.node_configs.networking.OVERLAY_IP }}'
  {{ end }}
  CONFIGURE_DNS: '{{ .Values.node_configs.networking.CONFIGURE_DNS | default "true" }}'

  ANYLOG_SERVER_PORT: '{{ .Values.node_configs.networking.ANYLOG_SERVER_PORT }}'
  TCP_BIND: '{{ .Values.node_configs.networking.TCP_BIND | default "false" }}'
  TCP_THREADS: '{{ .Values.node_configs.networking.TCP_THREADS | default 6 }}'

  ANYLOG_REST_PORT: '{{ .Values.node_configs.networking.ANYLOG_REST_PORT }}'
  REST_BIND: '{{ .Values.node_configs.networking.REST_BIND | default "false" }}'
  REST_TIMEOUT: '{{ .Values.node_configs.networking.REST_TIMEOUT | default 30 }}'
  REST_THREADS: '{{ .Values.node_configs.networking.REST_THREADS | default 30 }}'

  {{ - if .Values.node_configs.networking.ANYLOG_BROKER_PORT }}
  ANYLOG_BROKER_PORT: '{{ .Values.node_configs.networking.ANYLOG_BROKER_PORT }}'
  BROKER_BIND: '{{ .Values.node_configs.networking.BROKER_BIND | default "false" }}'
  BROKER_THREADS: '{{ .Values.node_configs.networking.BROKER_THREADS | default 6 }}'
  {{ end }}

  {{- if ne .Values.node_configs.networking.CONFIG_NAME "" }}
  CONFIG_NAME: '{{ .Values.node_configs.networking.CONFIG_NAME }}'
  {{ end }}

  # -- Database --
  DB_TYPE: '{{ .Values.node_configs.database.DB_TYPE | default "sqlite" }}'

  {{- if ne .Values.node_configs.database.DB_USER "" }}
  DB_USER: '{{ .Values.node_configs.database.DB_USER }}'
  {{ end }}
  {{- if ne .Values.node_configs.database.DB_PASSWD "" }}
  DB_PASSWD: '{{ .Values.node_configs.database.DB_PASSWD }}'
  {{ end }}
  DB_IP: '{{ .Values.node_configs.database.DB_IP }}'
  DB_PORT: '{{ .Values.node_configs.database.DB_PORT }}'
  AUTOCOMMIT: '{{ .Values.node_configs.database.AUTOCOMMIT }}'

  SYSTEM_QUERY: '{{ .Values.node_configs.database.SYSTEM_QUERY }}'
  MEMORY: '{{ .Values.node_configs.database.MEMORY }}'

  ENABLE_NOSQL: '{{ .Values.node_configs.database.ENABLE_NOSQL }}'
  NOSQL_TYPE: '{{ .Values.node_configs.database.NOSQL_TYPE }}'
  {{- if ne .Values.node_configs.database.NOSQL_USER "" }}
  NOSQL_USER: '{{ .Values.node_configs.database.NOSQL_USER }}'
  {{ end }}
  {{- if ne .Values.node_configs.database.NOSQL_PASSWD "" }}
  NOSQL_PASSWD: '{{ .Values.node_configs.database.DB_PASSWD }}'
  {{ end }}
  NOSQL_IP: '{{ .Values.node_configs.database.NOSQL_IP }}'
  NOSQL_PORT: '{{ .Values.node_configs.database.NOSQL_PORT }}'
  BLOBS_DBMS: '{{ .Values.node_configs.database.BLOBS_DBMS }}'
  BLOBS_REUSE: '{{ .Values.node_configs.database.BLOBS_REUSE }}'


  # -- Geolocation --
  {{- if ne .Values.node_configs.geolocation.LOCATION "" }}
  LOCATION: '{{ .Values.node_configs.geolocation.LOCATION }}'
  {{ end }}
  {{- if ne .Values.node_configs.geolocation.COUNTRY "" }}
  COUNTRY: '{{ .Values.node_configs.geolocation.COUNTRY }}'
  {{ end }}
  {{- if ne .Values.node_configs.geolocation.STATE "" }}
  STATE: '{{ .Values.node_configs.geolocation.STATE }}'
  {{ end }}
  {{- if ne .Values.node_configs.geolocation.CITY "" }}
  CITY: '{{ .Values.node_configs.geolocation.CITY }}'
  {{ end }}

  # -- blockchain --
  LEDGER_CONN: '{{ .Values.node_configs.blockchain.LEDGER_CONN }}'
  SYNC_TIME: '{{ .Values.node_configs.blockchain.SYNC_TIME }}'
  BLOCKCHAIN_SOURCE: '{{ .Values.node_configs.blockchain.BLOCKCHAIN_SOURCE }}'
  BLOCKCHAIN_DESTINATION: '{{ .Values.node_configs.blockchain.LEDGER_CONN }}'

  # -- operator ---
  CLUSTER_NAME: '{{ .Values.node_configs.operator.CLUSTER_NAME }}'
  DEFAULT_DBMS: '{{ .Values.node_configs.operator.DEFAULT_DBMS }}'

  {{- if ne .Values.node_configs.operator.MEMBER "" }}
  MEMBER: '{{ .Values.node_configs.operator.MEMBER }}'
  {{ end }}

  ENABLE_HA: '{{ .Values.node_configs.operator.ENABLE_HA | default "false" }}'
  START_DATE: '{{ .Values.node_configs.operator.START_DATE | default 30 }}'

  ENABLE_PARTITIONS: '{{ .Values.node_configs.operator.ENABLE_PARTITIONS | default "true" }}'
  {{- if ne .Values.node_configs.operator.TABLE_NAME "" }}
  TABLE_NAME: '{{ .Values.node_configs.operator.TABLE_NAME }}'
  {{ end }}
  PARTITION_COLUMN: '{{ .Values.node_configs.operator.PARTITION_COLUMN | default "insert_timestamp" }}'
  PARTITION_INTERVAL: '{{ .Values.node_configs.operator.PARTITION_INTERVAL | default "14 days" }}'
  PARTITION_KEEP: '{{ .Values.node_configs.operator.PARTITION_KEEP | default 3 }}'
  PARTITION_SYNC: '{{ .Values.node_configs.operator.PARTITION_SYNC | default 1 day }}'

  # -- MQTT --
  ENABLE_MQTT: '{{ .Values.node_configs.mqtt.ENABLE_MQTT | default "false" }}'
  MQTT_BROKER: '{{ .Values.node_configs.mqtt.MQTT_BROKER }}'
  MQTT_PORT: '{{ .Values.node_configs.mqtt.MQTT_PORT }}'
  MQTT_USER: '{{ .Values.node_configs.mqtt.MQTT_USER }}'
  MQTT_PASSWD: '{{ .Values.node_configs.mqtt.MQTT_PASSWD }}'
  MQTT_LOG: '{{ .Values.node_configs.mqtt.MQTT_LOG }}'
  MSG_TOPIC: '{{ .Values.node_configs.mqtt.MSG_TOPIC }}'
  MSG_DBMS: '{{ .Values.node_configs.mqtt.MSG_DBMS }}'
  MSG_TABLE: '{{ .Values.node_configs.mqtt.MSG_TABLE }}'
  MSG_TIMESTAMP_COLUMN: '{{ .Values.node_configs.mqtt.MSG_TIMESTAMP_COLUMN }}'
  MSG_VALUE_COLUMN: '{{ .Values.node_configs.mqtt.MSG_VALUE_COLUMN }}'
  MSG_VALUE_COLUMN_TYPE: '{{ .Values.node_configs.mqtt.MSG_VALUE_COLUMN_TYPE }}'

  # -- Monitoring --
  MONITOR_NODES: '{{ .Values.node_configs.monitoring.MONITOR_NODES | default "true" }}'
  STORE_MONITORING: '{{ .Values.node_configs.monitoring.STORE_MONITORING | default "false" }}'
  SYSLOG_MONITORING: '{{ .Values.node_configs.monitoring.SYSLOG_MONITORING | default "false" }}'

  #-- Advanced --
  COMPRESS_FILE: '{{ .Values.node_configs.advanced.COMPRESS_FILE | default "true" }}'
  QUERY_POOL: '{{ .Values.node_configs.advanced.QUERY_POOL | default 6 }}'
  WRITE_IMMEDIATE: '{{ .Values.node_configs.advanced.WRITE_IMMEDIATE | default "false" }}'
  THRESHOLD_TIME: '{{ .Values.node_configs.advanced.THRESHOLD_TIME | default "60 seconds" }}'
  THRESHOLD_VOLUME: '{{ .Values.node_configs.advanced.THRESHOLD_VOLUME | default "100KB" }}'

