metadata:
  # Kubernetes Instance namespace
  namespace: default
  # hostname for deployment
  hostname: anylog-node
  # deployment application name / Name of the AnyLog instance
  app_name: anylog-node
  service_name: anylog-node-service
  # Configuration file mapping name
  configmap_name: anylog-node-configmap
  # Allows running Kubernetes remotely. If commented out, code will ignore it
  node_selector: ""

image:
  # Image secret naming
  secret_name: imagepullsecret
  # (Docker Hub) Image Path
  repository: anylogco/anylog-network
  # Image version
  tag: latest
  # Image pulling policy
  pull_policy: IfNotPresent